export const MATCHMAKING_CONFIG = {
  BASE_RATING_RANGE: 300,
  RANGE_EXPANSION_PER_MINUTE: 20,
  WAITING_SCORE_REDUCTION_PER_MINUTE: 5,
  REMATCH_PENALTY: 250,
  RECENT_MATCH_LOOKBACK: 3,
} as const;
